title: Annabelle Laureen
logo: "images/me.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  School of Visual Arts BFA Illustration 2025
  <br><br>
  - Experience in Adobe Illustrator, Photoshop, Indesign, and Procreate
  <br><br>
  - Illustration, logo design, 2D animation, and social media management
  <br><br>
  - Doing commissions on Instagram since 2016
     <a href="https://www.instagram.com/bel_draws">View My Instagram Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
