title: Annabelle Laureen
logo: "images/Untitled_Artwork.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  School of Visual Arts BFA Illustration 2025
  <br><br>
  -2 years of experience in Adobe Illustrator, Photoshop, Indesign, and Procreate
  <br><br>
  -Experienced in illustration, logo design, social media management, and 2D animation
  <br><br>
  -Doing commissions on Instagram since 2016
  <br><br>
  <a href="https://www.instagram.com/bel_draws">View My Instagram Profile</a> 
  <br><br>
  <a href="https://www.youtube.com/channel/UCLlWkyJ8_YH0vyw8QoOpfdQ">View My Youtube Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
